#pragma once
// Generated by tools/generate_character_catalog.py; edit the source models or generator.
#ifdef OUTLAND_DEV_TOOLS
#include "outland/creator/CreatorAssetRegistry.hpp"
namespace outland::creator {
inline void register_character_assets(CreatorAssetRegistry& registry) {
    (void)registry.add({
        .id = "character_asset_first_person_arms_arms_rig", .name = "arms_rig",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/first_person_arms/arms_rig.glb", .thumbnail_path = "",
        .footprint = {1.677440F, 0.178463F, 0.487897F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "player_arms", "first_person"}
    });
    (void)registry.add({
        .id = "character_asset_first_person_arms_old_versions_psx_first_person_arms_free_2024_psx_first_person_arms", .name = "PSX_First_Person_Arms",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/first_person_arms/Old Versions/PSX_First_Person_Arms_Free (2024)/PSX_First_Person_Arms.glb", .thumbnail_path = "",
        .footprint = {1.621587F, 0.158869F, 0.462944F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "player_arms", "legacy_first_person"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_01", .name = "Character_01",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_01.glb", .thumbnail_path = "",
        .footprint = {0.646583F, 0.358983F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_02", .name = "Character_02",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_02.glb", .thumbnail_path = "",
        .footprint = {0.740632F, 0.372956F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_03", .name = "Character_03",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_03.glb", .thumbnail_path = "",
        .footprint = {0.648921F, 0.349458F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_04", .name = "Character_04",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_04.glb", .thumbnail_path = "",
        .footprint = {0.660064F, 0.366511F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_05", .name = "Character_05",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_05.glb", .thumbnail_path = "",
        .footprint = {0.662417F, 0.303758F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_06", .name = "Character_06",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_06.glb", .thumbnail_path = "",
        .footprint = {0.671752F, 0.303053F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_07", .name = "Character_07",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_07.glb", .thumbnail_path = "",
        .footprint = {0.677004F, 0.305181F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_08", .name = "Character_08",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_08.glb", .thumbnail_path = "",
        .footprint = {0.675913F, 0.309568F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_09", .name = "Character_09",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_09.glb", .thumbnail_path = "",
        .footprint = {0.695488F, 0.318533F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_10", .name = "Character_10",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_10.glb", .thumbnail_path = "",
        .footprint = {0.675709F, 0.309475F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_11", .name = "Character_11",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_11.glb", .thumbnail_path = "",
        .footprint = {0.669115F, 0.339771F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_12", .name = "Character_12",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_12.glb", .thumbnail_path = "",
        .footprint = {0.669574F, 0.333148F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_13", .name = "Character_13",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_13.glb", .thumbnail_path = "",
        .footprint = {0.660101F, 0.362705F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_14", .name = "Character_14",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_14.glb", .thumbnail_path = "",
        .footprint = {0.672496F, 0.372579F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_15", .name = "Character_15",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_15.glb", .thumbnail_path = "",
        .footprint = {0.661542F, 0.366510F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_16", .name = "Character_16",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_16.glb", .thumbnail_path = "",
        .footprint = {0.659780F, 0.354445F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_17_female_police", .name = "Character_17_Female_Police",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_17_Female_Police.glb", .thumbnail_path = "",
        .footprint = {0.926521F, 0.341728F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "emergency_police", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_17_police", .name = "Character_17_Police",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_17_Police.glb", .thumbnail_path = "",
        .footprint = {0.673627F, 0.331791F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "emergency_police", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_18_female_police", .name = "Character_18_Female_Police",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_18_Female_Police.glb", .thumbnail_path = "",
        .footprint = {1.073931F, 0.292504F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "emergency_police", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_18_police", .name = "Character_18_Police",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_18_Police.glb", .thumbnail_path = "",
        .footprint = {0.661542F, 0.366510F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "emergency_police", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_19_female_police", .name = "Character_19_Female_Police",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_19_Female_Police.glb", .thumbnail_path = "",
        .footprint = {0.926521F, 0.329108F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "emergency_police", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_19_police", .name = "Character_19_Police",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_19_Police.glb", .thumbnail_path = "",
        .footprint = {0.664313F, 0.327203F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "emergency_police", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_20_female_police", .name = "Character_20_Female_Police",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_20_Female_Police.glb", .thumbnail_path = "",
        .footprint = {1.073931F, 0.294158F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "emergency_police", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_20_police", .name = "Character_20_Police",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_20_Police.glb", .thumbnail_path = "",
        .footprint = {0.661541F, 0.366510F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "emergency_police", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_21_female_firefighter", .name = "Character_21_Female_Firefighter",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_21_Female_Firefighter.glb", .thumbnail_path = "",
        .footprint = {0.925058F, 0.338942F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "emergency_firefighter", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_21_police", .name = "Character_21_Police",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_21_Police.glb", .thumbnail_path = "",
        .footprint = {0.670298F, 0.371361F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "emergency_police", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_22_female_firefighter", .name = "Character_22_Female_Firefighter",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_22_Female_Firefighter.glb", .thumbnail_path = "",
        .footprint = {1.062027F, 0.311739F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "emergency_firefighter", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_22_police", .name = "Character_22_Police",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_22_Police.glb", .thumbnail_path = "",
        .footprint = {0.670336F, 0.330170F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "emergency_police", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_23_female_doctor", .name = "Character_23_Female_Doctor",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_23_Female_Doctor.glb", .thumbnail_path = "",
        .footprint = {0.926521F, 0.341398F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "emergency_doctor", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_23_firefighter", .name = "Character_23_Firefighter",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_23_Firefighter.glb", .thumbnail_path = "",
        .footprint = {0.701558F, 0.383424F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "emergency_firefighter", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_24_female_doctor", .name = "Character_24_Female_Doctor",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_24_Female_Doctor.glb", .thumbnail_path = "",
        .footprint = {1.073931F, 0.295041F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "emergency_doctor", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_24_firefighter", .name = "Character_24_Firefighter",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_24_Firefighter.glb", .thumbnail_path = "",
        .footprint = {0.722050F, 0.336568F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "emergency_firefighter", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_25_doctor", .name = "Character_25_Doctor",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_25_Doctor.glb", .thumbnail_path = "",
        .footprint = {0.661542F, 0.366510F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "emergency_doctor", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_25_female_police", .name = "Character_25_Female_Police",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_25_Female_Police.glb", .thumbnail_path = "",
        .footprint = {0.925370F, 0.319251F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "emergency_police", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_26_doctor", .name = "Character_26_Doctor",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_26_Doctor.glb", .thumbnail_path = "",
        .footprint = {0.674424F, 0.337452F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "emergency_doctor", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_26_female_police", .name = "Character_26_Female_Police",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_26_Female_Police.glb", .thumbnail_path = "",
        .footprint = {1.073931F, 0.294158F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "emergency_police", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_27_female_hm", .name = "Character_27_Female_HM",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_27_Female_HM.glb", .thumbnail_path = "",
        .footprint = {0.926521F, 0.316596F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_27_hm", .name = "Character_27_HM",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_27_HM.glb", .thumbnail_path = "",
        .footprint = {0.661542F, 0.373301F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_28_female_hm", .name = "Character_28_Female_HM",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_28_Female_HM.glb", .thumbnail_path = "",
        .footprint = {1.067083F, 0.315546F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_28_hm", .name = "Character_28_HM",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_28_HM.glb", .thumbnail_path = "",
        .footprint = {0.668484F, 0.360778F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_29", .name = "Character_29",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_29.glb", .thumbnail_path = "",
        .footprint = {0.652336F, 0.361409F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_29_female", .name = "Character_29_Female",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_29_Female.glb", .thumbnail_path = "",
        .footprint = {0.917857F, 0.331541F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_30", .name = "Character_30",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_30.glb", .thumbnail_path = "",
        .footprint = {0.664313F, 0.327203F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_30_female", .name = "Character_30_Female",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_30_Female.glb", .thumbnail_path = "",
        .footprint = {1.067102F, 0.335693F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_31", .name = "Character_31",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_31.glb", .thumbnail_path = "",
        .footprint = {0.663789F, 0.367755F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_31_female", .name = "Character_31_Female",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_31_Female.glb", .thumbnail_path = "",
        .footprint = {0.960463F, 0.346733F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_32", .name = "Character_32",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_32.glb", .thumbnail_path = "",
        .footprint = {0.664313F, 0.327203F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_32_female", .name = "Character_32_Female",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_32_Female.glb", .thumbnail_path = "",
        .footprint = {1.066533F, 0.335787F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_33_female", .name = "Character_33_Female",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_33_Female.glb", .thumbnail_path = "",
        .footprint = {1.059469F, 0.290197F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_female_01", .name = "Character_Female_01",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Female_01.glb", .thumbnail_path = "",
        .footprint = {1.102896F, 0.302092F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_female_02", .name = "Character_Female_02",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Female_02.glb", .thumbnail_path = "",
        .footprint = {0.910588F, 0.339741F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_female_03", .name = "Character_Female_03",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Female_03.glb", .thumbnail_path = "",
        .footprint = {0.926521F, 0.316596F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_female_04", .name = "Character_Female_04",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Female_04.glb", .thumbnail_path = "",
        .footprint = {0.921536F, 0.328038F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_female_05", .name = "Character_Female_05",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Female_05.glb", .thumbnail_path = "",
        .footprint = {0.921762F, 0.305418F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_female_06", .name = "Character_Female_06",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Female_06.glb", .thumbnail_path = "",
        .footprint = {1.068870F, 0.303864F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_female_07", .name = "Character_Female_07",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Female_07.glb", .thumbnail_path = "",
        .footprint = {0.949923F, 0.341551F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_female_08", .name = "Character_Female_08",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Female_08.glb", .thumbnail_path = "",
        .footprint = {0.926521F, 0.316596F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_female_09", .name = "Character_Female_09",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Female_09.glb", .thumbnail_path = "",
        .footprint = {0.926521F, 0.363111F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_female_10", .name = "Character_Female_10",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Female_10.glb", .thumbnail_path = "",
        .footprint = {1.073012F, 0.293907F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_female_11", .name = "Character_Female_11",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Female_11.glb", .thumbnail_path = "",
        .footprint = {0.942708F, 0.363266F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_female_12", .name = "Character_Female_12",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Female_12.glb", .thumbnail_path = "",
        .footprint = {1.068891F, 0.309397F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_female_13", .name = "Character_Female_13",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Female_13.glb", .thumbnail_path = "",
        .footprint = {0.966996F, 0.342576F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_female_14", .name = "Character_Female_14",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Female_14.glb", .thumbnail_path = "",
        .footprint = {1.061063F, 0.295919F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_female_15", .name = "Character_Female_15",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Female_15.glb", .thumbnail_path = "",
        .footprint = {0.926521F, 0.343137F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_female_16", .name = "Character_Female_16",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Female_16.glb", .thumbnail_path = "",
        .footprint = {1.073931F, 0.298984F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "civilian", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_killer", .name = "Character_Killer",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Killer.glb", .thumbnail_path = "",
        .footprint = {0.675403F, 0.353596F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "hostile", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_killer_01", .name = "Character_Killer_01",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Killer_01.glb", .thumbnail_path = "",
        .footprint = {0.660562F, 0.342510F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "hostile", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_killer_02", .name = "Character_Killer_02",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Killer_02.glb", .thumbnail_path = "",
        .footprint = {0.734771F, 0.340623F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "hostile", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_killer_03", .name = "Character_Killer_03",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Killer_03.glb", .thumbnail_path = "",
        .footprint = {0.672734F, 0.353024F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "hostile", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_killer_04", .name = "Character_Killer_04",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Killer_04.glb", .thumbnail_path = "",
        .footprint = {0.708612F, 0.339291F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "hostile", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_killer_05", .name = "Character_Killer_05",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Killer_05.glb", .thumbnail_path = "",
        .footprint = {0.653336F, 0.363411F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "hostile", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_killer_06", .name = "Character_Killer_06",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Killer_06.glb", .thumbnail_path = "",
        .footprint = {0.670376F, 0.344610F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "hostile", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_killer_07", .name = "Character_Killer_07",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Killer_07.glb", .thumbnail_path = "",
        .footprint = {0.665035F, 0.341063F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "hostile", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_monster", .name = "Character_Monster",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Monster.glb", .thumbnail_path = "",
        .footprint = {1.117135F, 0.303239F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "creature", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_monster_01", .name = "Character_Monster_01",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Monster_01.glb", .thumbnail_path = "",
        .footprint = {0.689448F, 0.405535F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "creature", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_monster_02", .name = "Character_Monster_02",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Monster_02.glb", .thumbnail_path = "",
        .footprint = {0.680760F, 0.357979F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "creature", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_monster_03", .name = "Character_Monster_03",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Monster_03.glb", .thumbnail_path = "",
        .footprint = {1.129031F, 0.335439F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "creature", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_monster_04", .name = "Character_Monster_04",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Monster_04.glb", .thumbnail_path = "",
        .footprint = {1.214942F, 0.631850F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "creature", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_psx_character_monster_05", .name = "Character_Monster_05",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/psx/Character_Monster_05.glb", .thumbnail_path = "",
        .footprint = {0.850013F, 0.303811F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "creature", "npc"}
    });
    (void)registry.add({
        .id = "character_asset_runtime_rebel_modern_rebel_soldier_character_models_modern_rebel_soldier_character", .name = "Modern Rebel Soldier Character",
        .category = CreatorAssetCategory::Prop,
        .model_path = "assets/verda/characters/runtime/rebel/Modern Rebel Soldier Character/Models/Modern Rebel Soldier Character.glb", .thumbnail_path = "",
        .footprint = {1.127794F, 0.323871F, 1.850000F}, .placement = {}, .default_scale = 1.0F,
        .tags = {"character", "hostile", "npc"}
    });
}
} // namespace outland::creator
#endif
