#pragma once
// Generated by tools/generate_city_kit.py - do not edit.
#include "outland/creator/CreatorAssetRegistry.hpp"
namespace outland::creator {
inline void register_city_assets(CreatorAssetRegistry& registry) {
    (void)registry.add({.id = "city_glass_dark_tower", .name = "Bank Tower (dark glass, 20 floors)", .category = CreatorAssetCategory::Building,
        .model_path = "assets/verda/city/towers/glass_dark_tower.glb", .thumbnail_path = "", .footprint = {24.00F, 24.00F, 77.50F},
        .placement = {}, .default_scale = 1, .tags = {"verda", "city", "downtown"}});
    (void)registry.add({.id = "city_glass_blue_tower", .name = "Office Tower (blue glass, 16 floors)", .category = CreatorAssetCategory::Building,
        .model_path = "assets/verda/city/towers/glass_blue_tower.glb", .thumbnail_path = "", .footprint = {22.00F, 26.00F, 63.10F},
        .placement = {}, .default_scale = 1, .tags = {"verda", "city", "downtown"}});
    (void)registry.add({.id = "city_stone_deco_tower", .name = "Art Deco Tower (stone, 14 floors)", .category = CreatorAssetCategory::Building,
        .model_path = "assets/verda/city/towers/stone_deco_tower.glb", .thumbnail_path = "", .footprint = {26.00F, 26.00F, 55.90F},
        .placement = {}, .default_scale = 1, .tags = {"verda", "city", "downtown"}});
    (void)registry.add({.id = "city_concrete_office", .name = "Concrete Office (8 floors)", .category = CreatorAssetCategory::Building,
        .model_path = "assets/verda/city/towers/concrete_office.glb", .thumbnail_path = "", .footprint = {30.00F, 22.00F, 34.30F},
        .placement = {}, .default_scale = 1, .tags = {"verda", "city", "downtown"}});
    (void)registry.add({.id = "city_brick_midrise", .name = "Brick Mid-rise (7 floors)", .category = CreatorAssetCategory::Building,
        .model_path = "assets/verda/city/towers/brick_midrise.glb", .thumbnail_path = "", .footprint = {24.00F, 20.00F, 30.70F},
        .placement = {}, .default_scale = 1, .tags = {"verda", "city", "downtown"}});
    (void)registry.add({.id = "city_stone_midrise", .name = "Stone Mid-rise (6 floors)", .category = CreatorAssetCategory::Building,
        .model_path = "assets/verda/city/towers/stone_midrise.glb", .thumbnail_path = "", .footprint = {20.00F, 24.00F, 27.10F},
        .placement = {}, .default_scale = 1, .tags = {"verda", "city", "downtown"}});
    (void)registry.add({.id = "city_glass_blue_midrise", .name = "Glass Mid-rise (9 floors)", .category = CreatorAssetCategory::Building,
        .model_path = "assets/verda/city/towers/glass_blue_midrise.glb", .thumbnail_path = "", .footprint = {28.00F, 20.00F, 37.90F},
        .placement = {}, .default_scale = 1, .tags = {"verda", "city", "downtown"}});
    (void)registry.add({.id = "city_main_street_red_12m_2st", .name = "Main Street Red Brick 12 m, 2 storeys (enterable)", .category = CreatorAssetCategory::Building,
        .model_path = "assets/verda/city/main_street/main_street_red_12m_2st.glb", .thumbnail_path = "", .footprint = {12.00F, 20.00F, 8.10F},
        .placement = {}, .default_scale = 1, .tags = {"verda", "city", "downtown"}});
    (void)registry.add({.id = "city_main_street_red_18m_3st", .name = "Main Street Red Brick 18 m, 3 storeys (enterable)", .category = CreatorAssetCategory::Building,
        .model_path = "assets/verda/city/main_street/main_street_red_18m_3st.glb", .thumbnail_path = "", .footprint = {18.00F, 20.00F, 11.70F},
        .placement = {}, .default_scale = 1, .tags = {"verda", "city", "downtown"}});
    (void)registry.add({.id = "city_main_street_red_12m_3st", .name = "Main Street Red Brick 12 m, 3 storeys (enterable)", .category = CreatorAssetCategory::Building,
        .model_path = "assets/verda/city/main_street/main_street_red_12m_3st.glb", .thumbnail_path = "", .footprint = {12.00F, 20.00F, 11.70F},
        .placement = {}, .default_scale = 1, .tags = {"verda", "city", "downtown"}});
    (void)registry.add({.id = "city_main_street_brown_12m_2st", .name = "Main Street Brown Brick 12 m, 2 storeys (enterable)", .category = CreatorAssetCategory::Building,
        .model_path = "assets/verda/city/main_street/main_street_brown_12m_2st.glb", .thumbnail_path = "", .footprint = {12.00F, 20.00F, 8.10F},
        .placement = {}, .default_scale = 1, .tags = {"verda", "city", "downtown"}});
    (void)registry.add({.id = "city_main_street_brown_18m_3st", .name = "Main Street Brown Brick 18 m, 3 storeys (enterable)", .category = CreatorAssetCategory::Building,
        .model_path = "assets/verda/city/main_street/main_street_brown_18m_3st.glb", .thumbnail_path = "", .footprint = {18.00F, 20.00F, 11.70F},
        .placement = {}, .default_scale = 1, .tags = {"verda", "city", "downtown"}});
    (void)registry.add({.id = "city_main_street_brown_12m_3st", .name = "Main Street Brown Brick 12 m, 3 storeys (enterable)", .category = CreatorAssetCategory::Building,
        .model_path = "assets/verda/city/main_street/main_street_brown_12m_3st.glb", .thumbnail_path = "", .footprint = {12.00F, 20.00F, 11.70F},
        .placement = {}, .default_scale = 1, .tags = {"verda", "city", "downtown"}});
    (void)registry.add({.id = "city_main_street_tan_12m_2st", .name = "Main Street Tan Brick 12 m, 2 storeys (enterable)", .category = CreatorAssetCategory::Building,
        .model_path = "assets/verda/city/main_street/main_street_tan_12m_2st.glb", .thumbnail_path = "", .footprint = {12.00F, 20.00F, 8.10F},
        .placement = {}, .default_scale = 1, .tags = {"verda", "city", "downtown"}});
    (void)registry.add({.id = "city_main_street_tan_18m_3st", .name = "Main Street Tan Brick 18 m, 3 storeys (enterable)", .category = CreatorAssetCategory::Building,
        .model_path = "assets/verda/city/main_street/main_street_tan_18m_3st.glb", .thumbnail_path = "", .footprint = {18.00F, 20.00F, 11.70F},
        .placement = {}, .default_scale = 1, .tags = {"verda", "city", "downtown"}});
    (void)registry.add({.id = "city_main_street_tan_12m_3st", .name = "Main Street Tan Brick 12 m, 3 storeys (enterable)", .category = CreatorAssetCategory::Building,
        .model_path = "assets/verda/city/main_street/main_street_tan_12m_3st.glb", .thumbnail_path = "", .footprint = {12.00F, 20.00F, 11.70F},
        .placement = {}, .default_scale = 1, .tags = {"verda", "city", "downtown"}});
    (void)registry.add({.id = "city_main_street_cream_12m_2st", .name = "Main Street Cream Brick 12 m, 2 storeys (enterable)", .category = CreatorAssetCategory::Building,
        .model_path = "assets/verda/city/main_street/main_street_cream_12m_2st.glb", .thumbnail_path = "", .footprint = {12.00F, 20.00F, 8.10F},
        .placement = {}, .default_scale = 1, .tags = {"verda", "city", "downtown"}});
    (void)registry.add({.id = "city_main_street_cream_18m_3st", .name = "Main Street Cream Brick 18 m, 3 storeys (enterable)", .category = CreatorAssetCategory::Building,
        .model_path = "assets/verda/city/main_street/main_street_cream_18m_3st.glb", .thumbnail_path = "", .footprint = {18.00F, 20.00F, 11.70F},
        .placement = {}, .default_scale = 1, .tags = {"verda", "city", "downtown"}});
    (void)registry.add({.id = "city_main_street_dark_12m_2st", .name = "Main Street Dark Brick 12 m, 2 storeys (enterable)", .category = CreatorAssetCategory::Building,
        .model_path = "assets/verda/city/main_street/main_street_dark_12m_2st.glb", .thumbnail_path = "", .footprint = {12.00F, 20.00F, 8.10F},
        .placement = {}, .default_scale = 1, .tags = {"verda", "city", "downtown"}});
    (void)registry.add({.id = "city_main_street_dark_18m_3st", .name = "Main Street Dark Brick 18 m, 3 storeys (enterable)", .category = CreatorAssetCategory::Building,
        .model_path = "assets/verda/city/main_street/main_street_dark_18m_3st.glb", .thumbnail_path = "", .footprint = {18.00F, 20.00F, 11.70F},
        .placement = {}, .default_scale = 1, .tags = {"verda", "city", "downtown"}});
    (void)registry.add({.id = "city_sidewalk_block_68", .name = "Sidewalk Block 68 m", .category = CreatorAssetCategory::BuildingPart,
        .model_path = "assets/verda/city/ground/sidewalk_block_68.glb", .thumbnail_path = "", .footprint = {68.00F, 68.00F, 0.15F},
        .placement = {}, .default_scale = 1, .tags = {"verda", "city", "downtown"}});
    (void)registry.add({.id = "city_courthouse_square_68", .name = "Courthouse Square Park 68 m", .category = CreatorAssetCategory::BuildingPart,
        .model_path = "assets/verda/city/ground/courthouse_square_68.glb", .thumbnail_path = "", .footprint = {68.00F, 68.00F, 4.60F},
        .placement = {}, .default_scale = 1, .tags = {"verda", "city", "downtown"}});
    (void)registry.add({.id = "city_parking_lot_68", .name = "Parking Lot 68 m", .category = CreatorAssetCategory::BuildingPart,
        .model_path = "assets/verda/city/ground/parking_lot_68.glb", .thumbnail_path = "", .footprint = {68.00F, 68.00F, 0.15F},
        .placement = {}, .default_scale = 1, .tags = {"verda", "city", "downtown"}});
    (void)registry.add({.id = "city_intersection_12", .name = "Street Intersection 12 m (crosswalks)", .category = CreatorAssetCategory::Road,
        .model_path = "assets/verda/city/ground/intersection_12.glb", .thumbnail_path = "", .footprint = {12.00F, 12.00F, 0.10F},
        .placement = {}, .default_scale = 1, .tags = {"verda", "city", "downtown"}});
}
}  // namespace outland::creator
