#pragma once
// Generated by tools/generate_starter_catalog.py.
#ifdef OUTLAND_DEV_TOOLS
#include "outland/creator/CreatorAssetRegistry.hpp"
namespace outland::creator {
inline void register_starter_assets(CreatorAssetRegistry& registry) {
    {
        const std::string path="assets/verda/starter/bush_round_lod0.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_bush_round_lod0", .name="Bush Round Lod0",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={2.080000F,1.370000F,1.100000F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/bush_round_lod1.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_bush_round_lod1", .name="Bush Round Lod1",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={1.680000F,1.102628F,1.100000F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/bush_round_lod2.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_bush_round_lod2", .name="Bush Round Lod2",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={1.018326F,0.906004F,0.960000F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/bush_scrub_lod0.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_bush_scrub_lod0", .name="Bush Scrub Lod0",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={2.870000F,1.560000F,0.710000F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/bush_scrub_lod1.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_bush_scrub_lod1", .name="Bush Scrub Lod1",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={2.250000F,1.204590F,0.710000F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/bush_scrub_lod2.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_bush_scrub_lod2", .name="Bush Scrub Lod2",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={1.253323F,0.955422F,0.640000F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/grass_field_lod0.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_grass_field_lod0", .name="Grass Field Lod0",
            .category=CreatorAssetCategory::Road, .model_path=path, .thumbnail_path="",
            .footprint={0.575592F,0.466189F,0.598329F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/grass_field_lod1.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_grass_field_lod1", .name="Grass Field Lod1",
            .category=CreatorAssetCategory::Road, .model_path=path, .thumbnail_path="",
            .footprint={0.477020F,0.356927F,0.598329F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/grass_field_lod2.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_grass_field_lod2", .name="Grass Field Lod2",
            .category=CreatorAssetCategory::Road, .model_path=path, .thumbnail_path="",
            .footprint={0.188164F,0.040020F,0.401421F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/grass_verge_lod0.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_grass_verge_lod0", .name="Grass Verge Lod0",
            .category=CreatorAssetCategory::Road, .model_path=path, .thumbnail_path="",
            .footprint={0.644839F,0.354168F,0.540734F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/grass_verge_lod1.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_grass_verge_lod1", .name="Grass Verge Lod1",
            .category=CreatorAssetCategory::Road, .model_path=path, .thumbnail_path="",
            .footprint={0.579277F,0.340158F,0.540734F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/grass_verge_lod2.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_grass_verge_lod2", .name="Grass Verge Lod2",
            .category=CreatorAssetCategory::Road, .model_path=path, .thumbnail_path="",
            .footprint={0.239599F,0.046559F,0.463093F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/ground_dirt_lod0.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_ground_dirt_lod0", .name="Ground Dirt Lod0",
            .category=CreatorAssetCategory::Road, .model_path=path, .thumbnail_path="",
            .footprint={4.000000F,4.000000F,0.010000F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/ground_dirt_lod1.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_ground_dirt_lod1", .name="Ground Dirt Lod1",
            .category=CreatorAssetCategory::Road, .model_path=path, .thumbnail_path="",
            .footprint={4.000000F,4.000000F,0.010000F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/ground_dirt_lod2.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_ground_dirt_lod2", .name="Ground Dirt Lod2",
            .category=CreatorAssetCategory::Road, .model_path=path, .thumbnail_path="",
            .footprint={4.000000F,4.000000F,0.010000F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/ground_grass_lod0.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_ground_grass_lod0", .name="Ground Grass Lod0",
            .category=CreatorAssetCategory::Road, .model_path=path, .thumbnail_path="",
            .footprint={4.000000F,4.000000F,0.010000F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/ground_grass_lod1.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_ground_grass_lod1", .name="Ground Grass Lod1",
            .category=CreatorAssetCategory::Road, .model_path=path, .thumbnail_path="",
            .footprint={4.000000F,4.000000F,0.010000F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/ground_grass_lod2.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_ground_grass_lod2", .name="Ground Grass Lod2",
            .category=CreatorAssetCategory::Road, .model_path=path, .thumbnail_path="",
            .footprint={4.000000F,4.000000F,0.010000F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/house_rural_lod0.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_house_rural_lod0", .name="House Rural Lod0",
            .category=CreatorAssetCategory::Building, .model_path=path, .thumbnail_path="",
            .footprint={8.820000F,8.510000F,6.840000F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/house_rural_lod1.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_house_rural_lod1", .name="House Rural Lod1",
            .category=CreatorAssetCategory::Building, .model_path=path, .thumbnail_path="",
            .footprint={8.700000F,7.700000F,6.840000F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/house_rural_lod2.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_house_rural_lod2", .name="House Rural Lod2",
            .category=CreatorAssetCategory::Building, .model_path=path, .thumbnail_path="",
            .footprint={8.700000F,7.700000F,6.200000F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/pebble_scatter_lod0.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_pebble_scatter_lod0", .name="Pebble Scatter Lod0",
            .category=CreatorAssetCategory::Road, .model_path=path, .thumbnail_path="",
            .footprint={1.919710F,1.490957F,0.135355F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/pebble_scatter_lod1.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_pebble_scatter_lod1", .name="Pebble Scatter Lod1",
            .category=CreatorAssetCategory::Road, .model_path=path, .thumbnail_path="",
            .footprint={1.809645F,1.466477F,0.135355F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/pebble_scatter_lod2.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_pebble_scatter_lod2", .name="Pebble Scatter Lod2",
            .category=CreatorAssetCategory::Road, .model_path=path, .thumbnail_path="",
            .footprint={1.809645F,0.778348F,0.124535F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/rock_boulder_lod0.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_rock_boulder_lod0", .name="Rock Boulder Lod0",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={2.583072F,1.769917F,1.900000F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/rock_boulder_lod1.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_rock_boulder_lod1", .name="Rock Boulder Lod1",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={2.513666F,1.532013F,1.900000F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/rock_boulder_lod2.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_rock_boulder_lod2", .name="Rock Boulder Lod2",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={2.108167F,1.584454F,1.900000F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/rock_field_lod0.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_rock_field_lod0", .name="Rock Field Lod0",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={1.136552F,0.825961F,0.680000F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/rock_field_lod1.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_rock_field_lod1", .name="Rock Field Lod1",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={1.106014F,0.714940F,0.680000F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/rock_field_lod2.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_rock_field_lod2", .name="Rock Field Lod2",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={0.927593F,0.739412F,0.680000F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/tree_oak_lod0.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_tree_oak_lod0", .name="Tree Oak Lod0",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={4.550000F,3.200000F,5.777976F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/tree_oak_lod1.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_tree_oak_lod1", .name="Tree Oak Lod1",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={3.850000F,2.818173F,5.777976F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/tree_oak_lod2.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_tree_oak_lod2", .name="Tree Oak Lod2",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={2.506648F,2.635646F,5.777976F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/tree_tall_lod0.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_tree_tall_lod0", .name="Tree Tall Lod0",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={4.550000F,3.200000F,6.567240F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/tree_tall_lod1.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_tree_tall_lod1", .name="Tree Tall Lod1",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={3.850000F,2.818173F,6.567240F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/tree_tall_lod2.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_tree_tall_lod2", .name="Tree Tall Lod2",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={2.506648F,2.635646F,6.567240F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/weapon_pistol_lod0.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_weapon_pistol_lod0", .name="Weapon Pistol Lod0",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={0.099000F,0.280000F,0.293500F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/weapon_pistol_lod1.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_weapon_pistol_lod1", .name="Weapon Pistol Lod1",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={0.090000F,0.280000F,0.293500F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/weapon_pistol_lod2.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_weapon_pistol_lod2", .name="Weapon Pistol Lod2",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={0.090000F,0.280000F,0.270000F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/weapon_rifle_lod0.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_weapon_rifle_lod0", .name="Weapon Rifle Lod0",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={0.168000F,0.850000F,0.395000F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/weapon_rifle_lod1.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_weapon_rifle_lod1", .name="Weapon Rifle Lod1",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={0.130000F,0.850000F,0.362500F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/weapon_rifle_lod2.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_weapon_rifle_lod2", .name="Weapon Rifle Lod2",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={0.130000F,0.850000F,0.330000F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/weed_lod0.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_weed_lod0", .name="Weed Lod0",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={0.644839F,0.346160F,1.028899F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/weed_lod1.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_weed_lod1", .name="Weed Lod1",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={0.424567F,0.148697F,1.028899F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
    {
        const std::string path="assets/verda/starter/weed_lod2.obj";
        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}
        if(!present)(void)registry.add({
            .id="starter_weed_lod2", .name="Weed Lod2",
            .category=CreatorAssetCategory::Nature, .model_path=path, .thumbnail_path="",
            .footprint={0.209599F,0.046559F,0.910281F}, .placement={}, .default_scale=1.0F,
            .tags={"starter","lod"}
        });
    }
}
}
#endif
