#pragma once
// Generated by tools/generate_survival_catalog.py.
#ifdef OUTLAND_DEV_TOOLS
#include "outland/creator/CreatorAssetRegistry.hpp"
namespace outland::creator {
inline void register_survival_assets(CreatorAssetRegistry& registry) {
    (void)registry.add({
        .id="survival_ammunition_f5ba1f58", .name="Survival Ammunition",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Ammunition.glb", .thumbnail_path="",
        .footprint={0.200730F,0.108879F,0.108879F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_antibiotics_b8d24268", .name="Survival Antibiotics",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Antibiotics.glb", .thumbnail_path="",
        .footprint={0.076036F,0.087798F,0.176513F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_antiseptic_ed9e16cc", .name="Survival Antiseptic",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Antiseptic.glb", .thumbnail_path="",
        .footprint={0.134219F,0.134219F,0.300762F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_axe_9e28648f", .name="Survival Axe",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Axe.glb", .thumbnail_path="",
        .footprint={0.309753F,0.052632F,0.764626F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_backpack_5118f76d", .name="Survival Backpack",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Backpack.glb", .thumbnail_path="",
        .footprint={0.882128F,0.732953F,0.799553F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_backpack_001_19a5af7b", .name="Survival Backpack.001",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Backpack.001.glb", .thumbnail_path="",
        .footprint={0.608346F,0.682203F,0.799553F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_battery_dfcb7c16", .name="Survival Battery",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Battery.glb", .thumbnail_path="",
        .footprint={0.042196F,0.040131F,0.121884F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_begal_ammunition_26513936", .name="Survival Begal ammunition",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Begal_ammunition.glb", .thumbnail_path="",
        .footprint={0.034414F,0.039737F,0.078957F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_bengal_b8b11aef", .name="Survival Bengal",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Bengal.glb", .thumbnail_path="",
        .footprint={0.273262F,0.049805F,0.287440F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_bengal_01_9561b5b8", .name="Survival Bengal 01",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Bengal_01.glb", .thumbnail_path="",
        .footprint={0.123841F,0.051476F,0.062758F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_bengal_02_6af21c87", .name="Survival Bengal 02",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Bengal_02.glb", .thumbnail_path="",
        .footprint={0.073442F,0.010000F,0.069606F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_bullet_65e6b63d", .name="Survival Bullet",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Bullet.glb", .thumbnail_path="",
        .footprint={0.113167F,0.015144F,0.015923F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_can_2dba9a87", .name="Survival Can",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Can.glb", .thumbnail_path="",
        .footprint={0.195979F,0.191065F,0.215518F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_can_soda_7c5b658f", .name="Survival Can Soda",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Can_Soda.glb", .thumbnail_path="",
        .footprint={0.135426F,0.156376F,0.249405F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_casserole_1a42a228", .name="Survival Casserole",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Casserole.glb", .thumbnail_path="",
        .footprint={0.440551F,0.547188F,0.251717F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_charger_fd351654", .name="Survival Charger",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Charger.glb", .thumbnail_path="",
        .footprint={0.126502F,0.032037F,0.117474F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_cup_1fb9305e", .name="Survival Cup",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Cup.glb", .thumbnail_path="",
        .footprint={0.265705F,0.203600F,0.197146F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_farol_2f7d653e", .name="Survival Farol",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Farol.glb", .thumbnail_path="",
        .footprint={0.262005F,0.309779F,0.595934F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_farol_g_469755d1", .name="Survival Farol G",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Farol_G.glb", .thumbnail_path="",
        .footprint={0.262005F,0.309779F,0.595934F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_glass_82c26818", .name="Survival Glass",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Glass.glb", .thumbnail_path="",
        .footprint={0.201548F,0.174546F,0.288141F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_handle_fa04ae3d", .name="Survival Handle",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Handle.glb", .thumbnail_path="",
        .footprint={0.294582F,0.294582F,0.388712F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_handle_001_dc1fa2b6", .name="Survival Handle.001",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Handle.001.glb", .thumbnail_path="",
        .footprint={0.294582F,0.294582F,0.388712F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_lantern_ee4b4532", .name="Survival Lantern",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Lantern.glb", .thumbnail_path="",
        .footprint={0.490111F,0.099484F,0.102042F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_shelter_tent_527f4e44", .name="Survival Shelter tent",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Shelter_tent.glb", .thumbnail_path="",
        .footprint={3.298107F,3.171263F,1.977411F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_torch_dcc578ac", .name="Survival Torch",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Torch.glb", .thumbnail_path="",
        .footprint={0.083693F,0.079597F,0.517681F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_trunk_10c81e7c", .name="Survival Trunk",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Trunk.glb", .thumbnail_path="",
        .footprint={0.443649F,0.436325F,0.385668F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_trunk_01_4fa91849", .name="Survival Trunk 01",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Trunk_01.glb", .thumbnail_path="",
        .footprint={0.272928F,0.949088F,0.270041F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_water_7ca7dea9", .name="Survival Water",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/Water.glb", .thumbnail_path="",
        .footprint={0.153458F,0.177198F,0.491698F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_band_65f15ce8", .name="Survival band",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/band.glb", .thumbnail_path="",
        .footprint={0.155222F,0.255488F,0.230176F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_bengal_dc01f18e", .name="Survival bengal",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/bengal.glb", .thumbnail_path="",
        .footprint={0.050846F,0.058712F,0.406875F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_bengal_01_4513eccc", .name="Survival bengal 01",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/bengal_01.glb", .thumbnail_path="",
        .footprint={0.041852F,0.048327F,0.361188F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_bonfire_c4172667", .name="Survival bonfire",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/bonfire.glb", .thumbnail_path="",
        .footprint={1.389015F,1.375581F,0.980684F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_branch_f38c764c", .name="Survival branch",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/branch.glb", .thumbnail_path="",
        .footprint={0.769885F,0.410043F,0.399024F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_branch_01_ed84a764", .name="Survival branch 01",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/branch_01.glb", .thumbnail_path="",
        .footprint={0.615527F,0.202421F,0.199332F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_hunting_rifle_408cfb25", .name="Survival hunting rifle",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/hunting_rifle.glb", .thumbnail_path="",
        .footprint={2.063926F,0.068574F,0.314768F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_hunting_rifle_01_652a79e9", .name="Survival hunting rifle 01",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/hunting_rifle_01.glb", .thumbnail_path="",
        .footprint={0.307981F,0.102864F,0.095385F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_knife_3d4d101c", .name="Survival knife",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/knife.glb", .thumbnail_path="",
        .footprint={0.095268F,0.026648F,0.442287F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_match_4945a70f", .name="Survival match",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/match.glb", .thumbnail_path="",
        .footprint={0.178510F,0.091670F,0.020392F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_match_01_ad60c901", .name="Survival match 01",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/match_01.glb", .thumbnail_path="",
        .footprint={0.158787F,0.010000F,0.010000F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_sleeping_bag_a33469c0", .name="Survival sleeping bag",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/sleeping_bag.glb", .thumbnail_path="",
        .footprint={0.920292F,1.957217F,0.181275F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_sleeping_bag_01_165d4165", .name="Survival sleeping bag 01",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/sleeping_bag_01.glb", .thumbnail_path="",
        .footprint={0.891740F,0.400948F,0.352412F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_trigger_683259fe", .name="Survival trigger",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/trigger.glb", .thumbnail_path="",
        .footprint={0.024077F,0.010000F,0.039878F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_zippo_479ff2e0", .name="Survival zippo",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/zippo.glb", .thumbnail_path="",
        .footprint={0.113121F,0.042458F,0.155449F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
    (void)registry.add({
        .id="survival_zippo_01_a9d68ba9", .name="Survival zippo 01",
        .category=CreatorAssetCategory::Prop, .model_path="assets/verda/survival/runtime/zippo_01.glb", .thumbnail_path="",
        .footprint={0.076080F,0.042461F,0.118851F}, .placement={}, .default_scale=1.0F,
        .tags={"survival","psx","prop"}
    });
}
}
#endif
