#!/usr/bin/env python3
"""Generate Creator entries for runtime GLBs; FBX/Blend copies remain source files."""
import argparse
import json
import re
from pathlib import Path
from gltf_import import read_gltf, scene_bounds
from character_manifest import read_manifest

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'include/outland/creator/CharacterAssetCatalog.hpp'
CATEGORIES = {'Buildings Prebuild': 'Building', 'Building Parts': 'BuildingPart',
              'Fences': 'BuildingPart', 'Walls & Fences': 'BuildingPart', 'Roads': 'Road'}


def generate():
    lines = ['#pragma once', '// Generated by tools/generate_character_catalog.py; edit the source models or generator.',
             '#ifdef OUTLAND_DEV_TOOLS', '#include "outland/creator/CreatorAssetRegistry.hpp"',
             'namespace outland::creator {', 'inline void register_character_assets(CreatorAssetRegistry& registry) {']
    ids = set()
    entries = read_manifest(ROOT)
    models = [ROOT / row['runtime_model'] for row in entries]
    if not models:
        raise ValueError('Character GLB pack is missing')
    for row, model in zip(entries, models):
        relative = model.relative_to(ROOT / 'assets/verda/characters')
        identifier = 'character_asset_' + re.sub('[^a-z0-9]+', '_', relative.with_suffix('').as_posix().lower()).strip('_')
        if identifier in ids:
            raise ValueError(f'Duplicate generated ID: {identifier}')
        ids.add(identifier)
        document, _ = read_gltf(model)
        low, high = scene_bounds(document)
        sizes = [high[axis] - low[axis] for axis in range(3)]
        if row['role'] == 'npc':
            sizes = [sizes[1], sizes[2], sizes[0]] if row['source'] == 'elbolilloduro_characters_psx' else sizes
            sizes = [size * 1.85 / max(.00001, sizes[1]) for size in sizes]
        dimensions = ', '.join(f'{max(.01, sizes[axis]):.6f}F' for axis in (0, 2, 1))
        category = 'Prop'
        quote = lambda text: json.dumps(str(text), ensure_ascii=True)
        lines += ['    (void)registry.add({',
                  f'        .id = {quote(identifier)}, .name = {quote(row['name'])},',
                  f'        .category = CreatorAssetCategory::{category},',
                  f'        .model_path = {quote(model.relative_to(ROOT).as_posix())}, .thumbnail_path = "",',
                  f'        .footprint = {{{dimensions}}}, .placement = {{}}, .default_scale = 1.0F,',
                  f'        .tags = {{"character", {quote(row['category'])}, {quote(row['role'])}}}', '    });']
    lines += ['}', '} // namespace outland::creator', '#endif', '']
    return '\n'.join(lines), len(models)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    content, count = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != content:
            raise SystemExit('Character catalogue is stale; run tools/generate_character_catalog.py')
    else:
        OUTPUT.write_text(content)
    print(f'Character catalogue: {count} models, unique IDs and transformed scene bounds verified.')


if __name__ == '__main__':
    main()
