#!/usr/bin/env python3
"""Generate Creator entries for runtime GLBs; FBX/Blend copies remain source files."""
import argparse
import json
import re
from pathlib import Path
from gltf_import import read_gltf, scene_bounds

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'include/outland/creator/UrbanAssetCatalog.hpp'
CATEGORIES = {'Buildings Prebuild': 'Building', 'Building Parts': 'BuildingPart',
              'Fences': 'BuildingPart', 'Walls & Fences': 'BuildingPart', 'Roads': 'Road'}


def generate():
    lines = ['#pragma once', '// Generated by tools/generate_urban_catalog.py; edit the source models or generator.',
             '#ifdef OUTLAND_DEV_TOOLS', '#include "outland/creator/CreatorAssetRegistry.hpp"',
             'namespace outland::creator {', 'inline void register_urban_assets(CreatorAssetRegistry& registry) {']
    ids = set()
    models = sorted((ROOT / 'assets/verda/urban').rglob('*.glb'))
    if not models:
        raise ValueError('Urban GLB pack is missing')
    for model in models:
        relative = model.relative_to(ROOT / 'assets/verda/urban')
        identifier = 'urban_' + re.sub('[^a-z0-9]+', '_', relative.with_suffix('').as_posix().lower()).strip('_')
        if identifier in ids:
            raise ValueError(f'Duplicate generated ID: {identifier}')
        ids.add(identifier)
        document, _ = read_gltf(model)
        low, high = scene_bounds(document)
        dimensions = ', '.join(f'{max(.01, high[axis] - low[axis]):.6f}F' for axis in (0, 2, 1))
        category = CATEGORIES.get(relative.parts[0], 'Prop')
        quote = lambda text: json.dumps(str(text), ensure_ascii=True)
        lines += ['    (void)registry.add({',
                  f'        .id = {quote(identifier)}, .name = {quote(model.stem.replace("_", " ").title())},',
                  f'        .category = CreatorAssetCategory::{category},',
                  f'        .model_path = {quote(model.relative_to(ROOT).as_posix())}, .thumbnail_path = "",',
                  f'        .footprint = {{{dimensions}}}, .placement = {{}}, .default_scale = 1.0F,',
                  f'        .tags = {{"urban", {quote(relative.parts[0])}}}', '    });']
    lines += ['}', '} // namespace outland::creator', '#endif', '']
    return '\n'.join(lines), len(models)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    content, count = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != content:
            raise SystemExit('Urban catalogue is stale; run tools/generate_urban_catalog.py')
    else:
        OUTPUT.write_text(content)
    print(f'Urban catalogue: {count} models, unique IDs and transformed scene bounds verified.')


if __name__ == '__main__':
    main()
