#!/usr/bin/env python3
"""Expose every starter OBJ/LOD through the existing Creator registry."""
import argparse,json,math
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUTPUT=ROOT/'include/outland/creator/StarterAssetCatalog.hpp'
def generate():
    lines=['#pragma once','// Generated by tools/generate_starter_catalog.py.','#ifdef OUTLAND_DEV_TOOLS','#include "outland/creator/CreatorAssetRegistry.hpp"','namespace outland::creator {','inline void register_starter_assets(CreatorAssetRegistry& registry) {']
    models=sorted((ROOT/'assets/verda/starter').glob('*.obj'))
    for model in models:
        points=[list(map(float,line.split()[1:4])) for line in model.read_text().splitlines() if line.startswith('v ')]
        if not points or not all(math.isfinite(v) for p in points for v in p):raise ValueError(f'Invalid OBJ: {model}')
        dimensions=[max(.01,max(p[axis] for p in points)-min(p[axis] for p in points)) for axis in (0,2,1)]
        path=model.relative_to(ROOT).as_posix();category='Building' if model.stem.startswith('house_') else 'Road' if model.stem.startswith(('ground_','grass_','pebble_')) else 'Nature'
        lines+=['    {',f'        const std::string path={json.dumps(path)};',
            '        bool present=false;for(const auto& asset:registry.assets())if(asset.model_path==path){present=true;break;}',
            '        if(!present)(void)registry.add({',f'            .id={json.dumps("starter_"+model.stem)}, .name={json.dumps(model.stem.replace("_"," ").title())},',
            f'            .category=CreatorAssetCategory::{category}, .model_path=path, .thumbnail_path="",',
            '            .footprint={'+','.join(f'{v:.6f}F' for v in dimensions)+'}, .placement={}, .default_scale=1.0F,',
            '            .tags={"starter","lod"}', '        });','    }']
    return '\n'.join(lines+['}','}','#endif','']),len(models)
if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args();text,count=generate()
    if args.check:
        assert OUTPUT.exists() and OUTPUT.read_text()==text,'Starter catalog is stale'
    else:OUTPUT.write_text(text)
    print(f'Starter catalog: {count} OBJ models/LODs, preserved existing IDs and measured footprints.')
