#!/usr/bin/env python3
"""Register converted Survival props and validate geometry/textures/source hashes."""
import argparse,hashlib,json
from pathlib import Path
from gltf_import import read_gltf,scene_bounds
ROOT=Path(__file__).resolve().parents[1]
OUTPUT=ROOT/'include/outland/creator/SurvivalAssetCatalog.hpp'
def generate():
    manifest=json.loads((ROOT/'assets/verda/survival/runtime_manifest.json').read_text())
    assert hashlib.sha256((ROOT/manifest['source']).read_bytes()).hexdigest()==manifest['source_sha256'],'Survival FBX changed; reconvert'
    for name,digest in manifest['texture_sha256'].items():
        assert hashlib.sha256((ROOT/'assets/verda/survival/Textures'/name).read_bytes()).hexdigest()==digest,'Survival textures changed; reconvert'
    lines=['#pragma once','// Generated by tools/generate_survival_catalog.py.','#ifdef OUTLAND_DEV_TOOLS','#include "outland/creator/CreatorAssetRegistry.hpp"','namespace outland::creator {','inline void register_survival_assets(CreatorAssetRegistry& registry) {']
    ids=set();images=0
    for entry in manifest['models']:
        assert entry['id'] not in ids;ids.add(entry['id'])
        path=ROOT/entry['model'];assert hashlib.sha256(path.read_bytes()).hexdigest()==entry['sha256'],'Converted Survival GLB changed'
        document,binary=read_gltf(path);low,high=scene_bounds(document)
        for image in document.get('images',[]):assert 'bufferView' in image and 'uri' not in image,'External/missing Survival texture'
        for material in document.get('materials',[]):
            if material.get('name')!='Glass':assert 'baseColorTexture' in material.get('pbrMetallicRoughness',{}),'Missing Survival base color'
        images+=len(document.get('images',[]))
        dimensions=','.join(f'{max(.01,high[axis]-low[axis]):.6f}F' for axis in (0,2,1))
        q=lambda value:json.dumps(value)
        lines+=['    (void)registry.add({',f'        .id={q(entry["id"])}, .name={q("Survival "+entry["name"])},',
            f'        .category=CreatorAssetCategory::Prop, .model_path={q(entry["model"])}, .thumbnail_path="",',
            f'        .footprint={{{dimensions}}}, .placement={{}}, .default_scale=1.0F,',
            '        .tags={"survival","psx","prop"}', '    });']
    assert len(list((ROOT/'assets/verda/survival/runtime').glob('*.glb')))==len(ids),'Uncatalogued Survival GLB'
    return '\n'.join(lines+['}','}','#endif','']),len(ids),images
if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args();content,count,images=generate()
    if args.check:assert OUTPUT.exists() and OUTPUT.read_text()==content,'Stale Survival catalog'
    else:OUTPUT.write_text(content)
    print(f'Survival catalog: {count} placeable GLBs, {images} embedded images, source/runtime hashes verified.')
